# name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:${EMULATOR_HTTP_PORT:-5300}"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA}
      EMULATOR_HTTP_PORT: ${EMULATOR_HTTP_PORT:-5300}
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL}
    depends_on:
      - mssql
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  mssql:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      sb-emulator:
        aliases:
          - "mssql"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"

networks:
  sb-emulator:
