version: 2
updates:
  - directory: "src/Altinn.Notifications"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
  - directory: "src/Altinn.Notifications.Functions"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
  - directory: "src/Altinn.Notifications.Integrations"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
  - directory: "src/Altinn.Notifications.Persistence"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
  - directory: "src/Altinn.Notifications.Interfaces"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
      
 ## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
  
