# Labels for pull requests

review/domain-model-changes:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - components/api/src/Altinn.Notifications.Core/Enums/*
      - components/api/src/Altinn.Notifications.Core/Models/*