# Labels for pull requests
review/component/shared:
  - changed-files:
      - any-glob-to-any-file:
          - components/shared/**

review/component/api:
  - changed-files:
      - any-glob-to-any-file:
          - components/api/**

review/component/email-service:
  - changed-files:
      - any-glob-to-any-file:
          - components/email-service/**

review/component/sms-service:
  - changed-files:
      - any-glob-to-any-file:
          - components/sms-service/**

review/domain-model-changes:
  - changed-files:
      - any-glob-to-any-file:
          - components/api/src/Altinn.Notifications.Core/Enums/*
          - components/api/src/Altinn.Notifications.Core/Models/*
          - components/sms-service/src/Altinn.Notifications.Sms.Core/Status/*
          - components/email-service/src/Altinn.Notifications.Email.Core/Models/*