{{- if .Values.ingress.enabled -}}
{{- $fullName := include "altinn-notifications.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "altinn-notifications.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  {{- range $entryPoint := .Values.ingress.entryPoints }}
  - {{ $entryPoint }}
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.match.host }}`) && PathPrefix(`{{ .Values.ingress.match.path }}`)
    {{- if .Values.linkerd.enabled }}
    middlewares:
    - name: {{ $fullName }}
    - name: hsts-header
    {{- end }}
    services:
    - name: {{ include "altinn-notifications.fullname" . }}
      port: {{ .Values.service.port }}
  tls:
    options:
      name: tls-options
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
