{{- if .Values.linkerd.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "altinn-notifications.fullname" . }}
spec: 
  headers:
    customRequestHeaders:
      l5d-dst-override: "{{ include "altinn-notifications.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local:{{.Values.service.port}}"
{{- end }}