SELECT
	NOTIFICATION_ADDRESS_ID,
	REGISTRY_ID,
	ADDRESS_TYPE,
	DOMAIN,
	ADDRESS,
	FULL_ADDRESS,
	CREATED_DATE_TIME,
	REGISTRY_UPDATED_DATE_TIME,
	UPDATE_SOURCE,
	HAS_REGISTRY_ACCEPTED,
	IS_SOFT_DELETED,
	NOTIFICATION_NAME,
	FK_REGISTRY_ORGANIZATION_ID
FROM
	ORGANIZATION_NOTIFICATION_ADDRESS.NOTIFICATIONS_ADDRESS
	where FULL_ADDRESS = '+4799999999'
LIMIT
	100;
	