GRANT  USAGE  ON SCHEMA notifications TO platform_notifications;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA notifications TO platform_notifications;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA notifications TO platform_notifications_admin;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA notifications TO platform_notifications;
GRANT ALL ON ALL SEQUENCES IN SCHEMA notifications TO platform_notifications;


