using Altinn.Notifications.Configuration;
using Altinn.Notifications.Core.Models.Notification;
using Altinn.Notifications.Core.Services.Interfaces;
using Altinn.Notifications.Core.Shared;
using Altinn.Notifications.Extensions;
using Altinn.Notifications.Mappers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Swashbuckle.AspNetCore.Annotations;

namespace Altinn.Notifications.Controllers
{
    /// <summary>
    /// Controller for all operations related to email notifications
    /// </summary>
    [Authorize(Policy = AuthorizationConstants.POLICY_CREATE_SCOPE_OR_PLATFORM_ACCESS)]
    [Route("notifications/api/v1/orders/{id}/notifications/email")]
    [ApiController]
    [SwaggerResponse(401, "Caller is unauthorized")]
    [SwaggerResponse(403, "Caller is not authorized to access the requested resource")]
    public class EmailNotificationsController : ControllerBase
    {
        private readonly IEmailNotificationSummaryService _summaryService;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailNotificationsController"/> class.
        /// </summary>
        /// <param name="summaryService">The notifications summary service</param>
        public EmailNotificationsController(IEmailNotificationSummaryService summaryService)
        {
            _summaryService = summaryService;
        }

        /// <summary>
        /// Get email notifications
        /// </summary>
        /// <remarks>
        /// Endpoint for retrieving the send status of all email notifications generated by a notification order.
        /// </remarks>
        /// <param name="id">The unique identifier of the notification order for which notifications are to be retrieved.</param>
        /// <returns>The email notifications were successfully retrieved.</returns>
        #pragma warning disable S1133
        [Obsolete("Legacy endpoint. Still supported, but going forward please use '/future/' endpoints instead.")]
        #pragma warning restore S1133
        [HttpGet]
        [Produces("application/json")]
        [SwaggerResponse(200, "The email notifications were successfully retrieved.", typeof(EmailNotificationSummaryExt))]
        [SwaggerResponse(404, "No order matching the provided ID was found.")]
        [SwaggerResponse(401, "Indicates a missing, invalid or expired authorization header.")]
        [SwaggerResponse(403, "Indicates missing or invalid scope or Platform Access Token.")]
        public async Task<ActionResult<EmailNotificationSummaryExt>> Get([FromRoute] Guid id)
        {
            string? expectedCreator = HttpContext.GetOrg();

            if (expectedCreator == null)
            {
                return Forbid();
            }

            Result<EmailNotificationSummary, ServiceError> result = await _summaryService.GetSummary(id, expectedCreator);

            return result.Match(
                summary => Ok(summary.MapToEmailNotificationSummaryExt()),
                error => StatusCode(error.ErrorCode, error.ErrorMessage));
        }
    }
}
