CREATE TABLE IF NOT EXISTS NOTIFICATIONS.DEADDELIVERYREPORTS (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	CHANNEL INT NOT NULL,
	DELIVERYREPORT JSONB NOT NULL,
	FIRSTSEEN TIMESTAMPTZ NOT NULL,
	LASTATTEMPT TIMESTAMPTZ NOT NULL,
	ATTEMPTCOUNT INT NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE NOTIFICATIONS.DEADDELIVERYREPORTS TO PLATFORM_NOTIFICATIONS;
