CREATE TABLE IF NOT EXISTS NOTIFICATIONS.DEADDELIVERYREPORTS (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CHANNEL INT NOT NULL,
	DELIVERYREPORT JSONB NOT NULL,
	FIRSTSEEN TIMESTAMPTZ NOT NULL,
	LASTATTEMPT TIMESTAMPTZ NOT NULL,
	RESOLVED BOOLEAN NOT NULL,
	ATTEMPTCOUNT INT NOT NULL CHECK (ATTEMPTCOUNT >= 0));

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE NOTIFICATIONS.DEADDELIVERYREPORTS TO PLATFORM_NOTIFICATIONS;
