name: build docker image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean
        default: true

jobs:
  docker-build:
    name: "build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get repository as lowercase
        id: lowercase
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ inputs.tag }}