name: build docker image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean
        default: true
    outputs:
      digest:
        description: "The docker image digest"
        value: ${{ jobs.docker-build.outputs.digest }}

jobs:
  docker-build:
    name: "build docker image"
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get repository as lowercase
        id: lowercase
        run: echo ::set-output name=image-repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build image
        id: build
        uses: docker/build-push-action@v3
        with:
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ steps.lowercase.outputs.image-repository }}:${{ inputs.tag }}
