name: deploy docker image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string
      digest:
        required: false
        type: string
        default: ""
      pullPolicy:
        required: false
        default: "IfNotPresent"
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AKS_RESOURCEGROUP_NAME:
        required: true
      AKS_CLUSTER_NAME:
        required: true
      TLS_SECRET_NAME:
        required: true
      INGRESS_HOST:
        required: true
      APPSETTINGS_SECRET_NAME:
        required: true
      APPSETTINGS_PATH:
        required: true
      DB_ADMIN_CONNECTION_STRING:
        required: true
      DB_USER_CONNECTION_STRING:
        required: true
      SMTP_HOST:
        required: true
      SMTP_SENDER:
        required: true

jobs:
  docker-build:
    name: "deploy to kubernetes"
    runs-on: ubuntu-latest
    environment: platform-${{ inputs.environment }}
    steps:
      - name: Setup helm
        uses: azure/setup-helm@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to ${{inputs.environment}}
        run: |
          curl -LO "https://github.com/Azure/kubelogin/releases/download/v0.0.10/kubelogin-linux-amd64.zip"
          sudo unzip -j "kubelogin-linux-amd64.zip" -d /usr/local/bin
          rm -rf "kubelogin-linux-amd64.zip"
          az aks get-credentials -g ${{ secrets.AKS_RESOURCEGROUP_NAME }} -n ${{ secrets.AKS_CLUSTER_NAME }}
          kubelogin convert-kubeconfig -l azurecli
          helm upgrade --install altinn-notifications ./chart/altinn-notifications \
            --set image.tag=${{inputs.tag}} \
            --set image.digest=${{inputs.digest}} \
            --set ingress.tls.secretName=${{secrets.TLS_SECRET_NAME}} \
            --set ingress.match.host=${{secrets.INGRESS_HOST}} \
            --set appsettings.mount=true \
            --set appsettings.secretName=${{secrets.APPSETTINGS_SECRET_NAME}} \
            --set appsettings.mountPath=${{secrets.APPSETTINGS_PATH}} \
            --set postgreSQLSettings.adminConnectionString=${{secrets.DB_ADMIN_CONNECTION_STRING}} \
            --set postgreSQLSettings.userConnectionString=${{secrets.DB_USER_CONNECTION_STRING}} \
            --set image.pullPolicy=${{inputs.pullPolicy}} \
            --set smtpSettings.host=${{secrets.SMTP_HOST}} \
            --set smtpSettings.sender=${{secrets.SMTP_SENDER}}
          kubectl wait --for=condition=available --timeout=600s deployment/altinn-notifications
          helm test altinn-notifications
      - name: Post Deploy
        if: always()
        run: |
          rm -rf /home/runner/.kube/config
          az logout
          az account clear
