name: Label PR by component
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'components/api/**'
      - 'components/email-service/**'
      - 'components/sms-service/**'
      - 'components/shared/**'
      - 'tools/**'

jobs:
  add_component_labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
