name: Label critical PR
on:
  pull_request_target:
    branches:
      -  main
    types:
      - opened
    paths:
      - '**/Altinn.Notifications.Core/**'

jobs:
  add_labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
