name: Label critical PR
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
    paths:
      - '**/Altinn.Notifications.Core/**'

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
