name: Regression test - AT


on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TOKENGENERATOR_USERNAME:
        required: true
      TOKENGENERATOR_USERPASSWORD:
        required: true
      AUTOMATEDTEST_EMAILRECIPIENT:
        required: true
      SLACK_WEBHOOK_URL_TEST:
        required: true

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4
    - name: Run email notification order regression tests
      uses: grafana/k6-action@v0.3.1
      with:
        filename: test/k6/src/tests/orders_email.js
        flags: -e runFullTestSet=true -e env=${{ vars.ENV }} -e tokenGeneratorUserName=${{ secrets.TOKENGENERATOR_USERNAME }} -e tokenGeneratorUserPwd=${{ secrets.TOKENGENERATOR_USERPASSWORD }} -e emailRecipient=${{ secrets.AUTOMATEDTEST_EMAILRECIPIENT }}
    - name: Build failure report
      if: failure()
      run: |
          report=":warning: Notifications regression test failure in ${{ inputs.environment }} :warning: \n"
          report+="\n Workflow available here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "stepreport="$report >> $GITHUB_ENV
    - name: Report failure to Slack
      if: failure()
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
            {
              "text": "${{ env.stepreport }}"
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}

